# Generated by Django 5.0.1 on 2024-03-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0005_myorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_img',
            new_name='img',
        ),
    ]
